Add a lightweight implementation of atoi(3)
newlib implementation of atoi() depends of strtol(). strtol() depends
on strtol_l(). strtol_l() depends on locales. locales are bloated and
depend on malloc and file IO.

These dependencies break compilation like this:
newlib/libc/reent/closer.c:46: undefined reference to `_close'
newlib/libc/reent/lseekr.c:48: undefined reference to `_lseek'
newlib/libc/reent/readr.c:48: undefined reference to `_read'
newlib/libc/reent/writer.c:48: undefined reference to `_write'
newlib/libc/reent/sbrkr.c:50: undefined reference to `_sbrk'

Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>